// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD--66s-BbN3XP6pm9TW7EdDPnRNYb-r_E',
    appId: '1:584226897907:web:71d2257605bbd0b39fdc86',
    messagingSenderId: '584226897907',
    projectId: 'bodywise-d8163',
    authDomain: 'bodywise-d8163.firebaseapp.com',
    storageBucket: 'bodywise-d8163.appspot.com',
    measurementId: 'G-H78S8CX2QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo4dUCdL0637dwra2ZkMz6q9gP9yW6x3I',
    appId: '1:584226897907:android:14606603598d78889fdc86',
    messagingSenderId: '584226897907',
    projectId: 'bodywise-d8163',
    storageBucket: 'bodywise-d8163.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7osmLMWLUG3Hws67SeeDO7P9O967EswU',
    appId: '1:584226897907:ios:d19904660f5880709fdc86',
    messagingSenderId: '584226897907',
    projectId: 'bodywise-d8163',
    storageBucket: 'bodywise-d8163.appspot.com',
    iosBundleId: 'com.example.bodyWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7osmLMWLUG3Hws67SeeDO7P9O967EswU',
    appId: '1:584226897907:ios:5dade2d30bb38c169fdc86',
    messagingSenderId: '584226897907',
    projectId: 'bodywise-d8163',
    storageBucket: 'bodywise-d8163.appspot.com',
    iosBundleId: 'com.example.bodyWise.RunnerTests',
  );
}
